management:
  endpoint:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: env
spring:
  cloud:
    bus:
      env:
        enabled: true
      refresh:
        enabled: true
      id: "${vcap.application.name:${spring.application.name:application}:${spring.profiles.active}},${spring.profiles.include}:${vcap.application.instance_index:${spring.application.index:${local.server.port:${server.port:0}}}}:${vcap.application.instance_id:${random.value}}"
